### ISSUE TITLE
How to look for values in `import.meta.env`

### ISSUE THREAD

**Issue by giacomorebonato** [KeJunMao/vite-plugin-conditional-compile#11]
Vite injects its env vars in `import.meta.env`, how can we tell this plugin to look in that place?

**Comment by KeJunMao** [comment]
`import.meta.env` is the runtime environment variable.

This plugin is processed at build time

**Comment by KeJunMao** [comment]
In a nutshell, the environment context for this plugin is:
- System variables at build time, eg: `PATH`, `HOME`,`JAVA_HOME`...
- Vite supplied variables, which contain the built-in environment variables (`BASE_URL`, `MODE`, `DEV`, `PROD`) and the[ `.env` file](https://vitejs.dev/guide/env-and-mode#env-files)

**Comment by giacomorebonato** [comment]
The context of my work is that I am practicing with [Vavite](https://github.com/cyco130/vavite) to create my custom NextJS framework.
Vavite makes sense to me because I use one instance of Vite server to compile both client and server TS code.

So I have a command `vavite build` that compiles both server and client, hence I can't use an env var, which will end up on both client/server build.

Is there anything in Vite that can understand the `use server` directive which comes up in the way NextJS implements React Server Components?

**Comment by giacomorebonato** [comment]
Thanks for helping and for the information. I'll keep researching
