### ISSUE TITLE
Increase in build time when using the plugin

### ISSUE THREAD

**Issue by ManHunter** [KeJunMao/vite-plugin-conditional-compile#12]
Hello, thank you very much for the plugin.
Can you tell me for what reasons the build time may increase?

With conditional compile (4m. 25sec.):
![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/7999492/8f1cdf9b-8be0-4179-ae76-6087d72ef7e0)

Without conditional compile (2.72sec.):
![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/7999492/1c5410ca-4c6b-455a-862c-d71b9e461789)

**Comment by KeJunMao** [comment]
I'm sorry for the performance issue. I'm trying to develop conditional compilation based on AST. Would you like to try and test its performance?

https://github.com/KeJunMao/unplugin-preprocessor-directives/tree/feat/ast

**Comment by KeJunMao** [comment]
@ManHunter Sorry to bother you, could you please try the latest version?

I tried to process all files of 10000 fixtures (10000 * 5 files) locally, which took 3 seconds

**Comment by ManHunter** [comment]
Hi @KeJunMao, sorry for the delay, I tested and now the build takes 3.85 sec 🔥🔥🔥 Thank you 🙏
