### ISSUE TITLE
Can NOT create breakpoint

### ISSUE THREAD

**Issue by gaokun** [KeJunMao/vite-plugin-conditional-compile#14]
Version: 0.3.0

# use plugin
## every line is disabled, can't create a breakpoint

![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/7044628/d0fc86d6-b041-4b02-8076-74c2bbea02bd)

# no plugin 

## can create breakpoint, notice the color different between lines.

![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/7044628/16b42674-cfd9-4a92-892d-3ee16ae3bc88)

**Comment by KeJunMao** [comment]
try v0.3.1

**Comment by gaokun** [comment]
@KeJunMao 
works now. Thanks for quick fix.
