### ISSUE TITLE
Dose it support VITE_MY_ENV!=hi ?

### ISSUE THREAD

**Issue by gaokun** [KeJunMao/vite-plugin-conditional-compile#2]
Hi,
  According to the source code, I can't use it like: 
```
// #v-ifdef VITE_MY_ENV!=hi
```

But I can use below code instead, right?
```
// #v-ifndef VITE_MY_ENV=hi
```

Do you have a plan to support '!=' ?

Thanks

**Comment by KeJunMao** [comment]
emmm, sorry, i think support `!=` is not a good ideas.

Forget about performance, If I support '!=', Do you still have to support `!VITE_MY_ENV` and `// #v-ifndef VITE_MY_ENV!=hi`, This will make the syntax too complex.

ps: Why do you need `!=`
