### ISSUE TITLE
Implement #v-else

### ISSUE THREAD

**Issue by VororRich** [KeJunMao/vite-plugin-conditional-compile#4]
I would be great if you could implement #v-else for clarity.  Instead of...
```
// #v-ifdef VITE_PRO
    ... pro features ...
// #v-endif

// #v-ifndef VITE_PRO
  ... free features ...
// #v-endif
```

You could instead do...
```
// #v-ifdef VITE_PRO
    ... pro features ...
// #v-else
  ... free features ...
// #v-endif
```

**Comment by KeJunMao** [comment]
Good note, I'll try it later.

However, the library is implemented with a regex, so it's not clear if I can do it for now.
