### ISSUE TITLE
Doesn't work as expected in dev mode

### ISSUE THREAD

**Issue by VororRich** [KeJunMao/vite-plugin-conditional-compile#5]
I'm using this to conditionally import FontAwesome pro.
I have a #v-ifdef around a whole file content...
```
// @ts-nocheck
// #v-ifdef VITE_FONT_AWESOME_PACKAGE_TOKEN
import {Library} from '@fortawesome/fontawesome-svg-core';

import { faXmark } from "@fortawesome/pro-regular-svg-icons/faXmark";
import { faAngleLeft } from "@fortawesome/pro-regular-svg-icons/faAngleLeft";
import { faAngleRight } from "@fortawesome/pro-regular-svg-icons/faAngleRight";
import { faStar } from "@fortawesome/pro-regular-svg-icons/faStar";
import { faGrid2 } from "@fortawesome/pro-regular-svg-icons/faGrid2";
import { faUser } from "@fortawesome/pro-regular-svg-icons/faUser";

export default function addRegularIcons(library: Library) {
  library.add(
    faXmark,
    faAngleLeft,
    faAngleRight,
    faStar,
    faGrid2,
    faUser
  );
}
// #v-endif
```
Works great in build mode (`vite build`) but in dev mode (`vite`) it's still trying to run the imports, giving `The following dependencies are imported but could not be resolved:` errors.

**Comment by KeJunMao** [comment]
Ok, let me check it

**Comment by KeJunMao** [comment]
Looks like you're using an outdated version,pls try `v0.1.1`

**Comment by VororRich** [comment]
Thanks for the response.  Still have the problem on `v0.1.1` I'm afraid.

**Comment by VororRich** [comment]
Apologies, scratch that - rogue package-lock.json - looks like working as expected in `v0.1.1`.

**Comment by VororRich** [comment]
Not working again this morning.  Looks like it may be an intermittent problem.  Confirmed definitely on v0.1.1
![image](https://user-images.githubusercontent.com/10374645/224958416-62156bc0-3a09-4a59-b187-47a4bdbde5fd.png)

**Comment by KeJunMao** [comment]
can you give me a [minimal-reproducible](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by VororRich** [comment]
I'll try create a minimal later today.  In the mean time (if its of any use) I'm using as part of a (quite large) open source project.  Source available here...
https://github.com/endeavourhealth-discovery/IMDirectory
cd into ui, `npm i`, `npm run dev:vite` and you should see it.

**Comment by VororRich** [comment]
Minimal on a branch here...
https://github.com/endeavourhealth-discovery/IMDirectory/tree/minimal-conditional-compile

It looks like its a vite thing (cache maybe).  It throws out the warnings to start but once you run/load the app in a browser, I can see the conditionals log, then subsequent runs dont display the warnings.

**Comment by VororRich** [comment]
Confirmed - errors reappear on delete of node_modules and reinstall.
![image](https://user-images.githubusercontent.com/10374645/224978679-978f50da-3f38-46d4-8919-686883d281ee.png)
