### ISSUE TITLE
`&&` operator support

### ISSUE THREAD

**Issue by iamskok** [KeJunMao/vite-plugin-conditional-compile#6]
Thanks for the plugin! Do you have any plans to support `&&` operator?

**Comment by KeJunMao** [comment]
sorry, no plan for now. but I will investigate how to support it

**Comment by iamskok** [comment]
Thanks for your quick reply! Do you know why this hack is not working?

```
/* #v-ifdef VITE_XYZ */
/* #v-ifdef VITE_ZYX */
export const x = 'VITE_XYZ && VITE_ZYX is set';
/* #v-endif */
/* #v-endif */
```

**Comment by KeJunMao** [comment]
This plugins uses regex matching, Unable to support nested.
```js
/^.*?#v-if(n?)def\s*(\S+).*[\r\n]{1,2}([\s\S]+?)\s*.*?#v-endif.*?$/gm
```
```diff
+/* #v-ifdef VITE_XYZ */
+/* #v-ifdef VITE_ZYX */
+export const x = 'VITE_XYZ && VITE_ZYX is set';
+/* #v-endif */
/* #v-endif */
```

**Comment by KeJunMao** [comment]
hi, see this https://github.com/KeJunMao/unplugin-preprocessor-directives

**Comment by iamskok** [comment]
@KeJunMao, what is the main difference between these two plugins?

**Comment by KeJunMao** [comment]
[unplugin-preprocessor-directives](https://github.com/KeJunMao/unplugin-preprocessor-directives) used xregex and eval(`new Function`), so support nested syntax, and any javascript conditional expression
