### ISSUE TITLE
为什么刷新的时间会变的特别长 Why does the refresh time become so long?

### ISSUE THREAD

**Issue by a982246809** [KeJunMao/vite-plugin-conditional-compile#8]
为什么刷新的时间会变的特别长 Why does the refresh time become so long?

**Comment by KeJunMao** [comment]
啥意思？变慢了吗？试试配置 include 为 src，或者用 exclude 排除一些目录

**Comment by a982246809** [comment]
我装上这个插件后 , 刷新要好久才显示 
![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/56909676/b002ad59-932b-4b9e-a92f-9fca1d4d75fb)
这么使用没问题吧

**Comment by KeJunMao** [comment]
没问题呀，应该很快就处理好了呀，你能提供一个最小复现吗？

**Comment by a982246809** [comment]
怎么提供

**Comment by KeJunMao** [comment]
https://www.zhihu.com/tardis/zm/art/499631365?source_id=1005

**Comment by a982246809** [comment]
解决了 把node_module删了 重install了下  , 就好了
我猜是vite的缓存有问题

**Comment by a982246809** [comment]
用了一会 , 刷新又变长了

**Comment by KeJunMao** [comment]
更新了一版，默认把 node_modules 排除了，你可以试试

**Comment by a982246809** [comment]
这个插件为什么会依赖rollup@3

**Comment by KeJunMao** [comment]
> 这个插件为什么会依赖rollup@3

因为自 v0.2.0 开始, 这个插件本质上是[unplugin-preprocessor-directives](https://github.com/KeJunMao/unplugin-preprocessor-directives)的封装.

**Comment by a982246809** [comment]
还是刷新时间很长怎么办  ;  第一次重装node_modules 刷新不卡 , 重启vite后 , 刷新就变的很卡了 ,

**Comment by a982246809** [comment]
直接把我cpu风扇干的做死的转

**Comment by KeJunMao** [comment]
更新到最新版了吗，能把你的 vite.config 给我看下吗

**Comment by a982246809** [comment]
/// <reference types="vitest" />
import { defineConfig, loadEnv } from 'vite';
import { resolve } from 'path';
import presets from './presets/presets';

// https://vitejs.dev/config/
export default defineConfig((env) => {
  // env 环境变量
  const viteEnv = loadEnv(env.mode, process.cwd());

  // console.log("🚀  resolve(__dirname, './src'):", resolve(__dirname, './src'));
  // console.log("🚀 resolve(__dirname, 'src/assets/img'):", resolve(__dirname, 'src/assets/img'));

  return {
    base: viteEnv.VITE_BASE,
    // 插件
    plugins: [presets(env, viteEnv)],
    test: {
      deps: {
        interopDefault: true,
        // inline: true,
      },
      // open: true,
      browser: {
        enabled: true,
      },
    },
    // 别名设置
    resolve: {
      alias: {
        // '!': (res) => {
        //   console.log('🚀  res:', res);
        // },
        '@': resolve(__dirname, './src'), // 把 @ 指向到 src 目录去

        '!': resolve(__dirname, 'src/assets/img'), //! 还不可使用
      },
    },
    // 服务设置
    server: {
      // https: true,
      host: true, // host设置为true才可以使用network的形式，以ip访问项目
      port: 8080, // 端口号
      // open: true, // 自动打开浏览器
      cors: true, // 跨域设置允许
      strictPort: true, // 如果端口已占用直接退出
      // 接口代理
      //! 没起作用
      proxy: {
        '/api': {
          // 本地 8000 前端代码的接口 代理到 8888 的服务端口
          target: 'http://localhost:8888/',
          changeOrigin: true, // 允许跨域
          rewrite: (path) => path.replace('/api/', '/'),
        },
        // 走本地接口
        // [process.env.VUE_APP_BASE_API]: {
        //   target: process.env.VUE_APP_BASE_TARGET,
        //   changeOrigin: true,
        //   pathRewrite: {
        //     ['^' + process.env.VUE_APP_BASE_API]: ''
        //   }
        // }
      },
    },
    build: {
      reportCompressedSize: false,
      // 消除打包大小超过500kb警告
      chunkSizeWarningLimit: 2000,
      minify: 'esbuild',
      assetsDir: 'static/assets',
      // 静态资源打包到dist下的不同目录
      rollupOptions: {
        output: {
          chunkFileNames: 'static/js/[name]-[hash].js',
          entryFileNames: 'static/js/[name]-[hash].js',
          assetFileNames: 'static/[ext]/[name]-[hash].[ext]',
        },
      },
    },
    css: {
      preprocessorOptions: {
        // 全局引入了 scss 的文件
        scss: {
          additionalData: `
          @import "@/assets/styles/variables.scss";
        `,
          javascriptEnabled: true,
        },
      },
    },
    define: {
      __Package_VERSION__: JSON.stringify(process.env.npm_package_version),
    },
  };
});

**Comment by a982246809** [comment]
这是插件的presets文件

import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import svgLoader from 'vite-svg-loader';
import AutoImport from 'unplugin-auto-import/vite';
import Components from 'unplugin-vue-components/vite';
import Icons from 'unplugin-icons/vite';
// loader helpers
import { FileSystemIconLoader } from 'unplugin-icons/loaders'
import IconsResolver from 'unplugin-icons/resolver';
import { ElementPlusResolver, VantResolver, VueUseComponentsResolver, HeadlessUiResolver, NaiveUiResolver } from 'unplugin-vue-components/resolvers';

import Markdown from 'vite-plugin-vue-markdown'
import Prism from 'markdown-it-prism';
import ViteFonts from 'vite-plugin-fonts';
// import VueI18n from '@intlify/vite-plugin-vue-i18n';
import VueI18n from '@intlify/unplugin-vue-i18n/vite'
import LinkAttributes from 'markdown-it-link-attributes';
import Unocss from 'unocss/vite'
import { ConfigEnv } from 'vite';
import { resolve } from 'path';
import mkcert from 'vite-plugin-mkcert'
import { VitePWA } from 'vite-plugin-pwa'
import ConditionalCompile from "vite-plugin-conditional-compiler";
const defaultClasses = 'prose prose-sm m-auto text-left';

export default (env: ConfigEnv, viteEnv) => {
  return [

    VitePWA({
      devOptions: {
        // enabled: true
        /* other options */
      },
      registerType: 'autoUpdate',
      manifest: {
        "name": viteEnv.VITE_APP_TITLE,
        "short_name": viteEnv.VITE_APP_TITLE,
        "start_url": ".",
        "display": "standalone",
        "background_color": "#1f1f1f",
        "description": viteEnv.VITE_APP_TITLE,
        "icons": [
          // {
          //   "src": "favicon.png",
          //   "sizes": "144x144",
          //   "type": "image/png"
          // },
          {
            "src": "favicon.png",
            "sizes": "72x72",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "96x96",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "144x144",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "168x168",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "192x192",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "256x256",
            "type": "image/png"
          }
        ]
      }
    }),
    vue({
      include: [/\.vue$/, /\.md$/],
      template: {
        // 解决警告
        // Failed to resolve component: swiper-container
        // If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
        compilerOptions: {
          isCustomElement: (tag) => ['swiper-container', 'swiper-slide'].includes(tag),
        },
      }

    }),
    vueJsx(),
    svgLoader(),
    AutoImport({
      dts: './src/auto-imports.d.ts',
      imports: ['vue', 'pinia', 'vue-router', 'vue-i18n', , '@vueuse/core', {
        'naive-ui': [
          'useDialog',
          'useMessage',
          'useNotification',
          'useLoadingBar'
        ]
      }],
      // Generate corresponding .eslintrc-auto-import.json file.
      // eslint globals Docs - https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals
      eslintrc: {
        enabled: false, // Default `false`
        filepath: './.eslintrc-auto-import.json', // Default `./.eslintrc-auto-import.json`
        globalsPropValue: true, // Default `true`, (true | false | 'readonly' | 'readable' | 'writable' | 'writeable')
      },
      resolvers: [ElementPlusResolver()],
    }),
    Components({
      dts: './src/components.d.ts',
      extensions: ['vue', 'md', 'svg'],
      include: [/\.vue$/, /\.vue\?vue/, /\.md$/,],
      // imports 指定组件所在位置，默认为 src/components; 有需要也可以加上 view 目录
      // dirs: ['src/components/'],
      dirs: ['src'],
      resolvers: [ElementPlusResolver(), IconsResolver({
        customCollections: [
          'my-icons',
        ],
      }), VueUseComponentsResolver(), HeadlessUiResolver(), NaiveUiResolver(), VantResolver()],
    }),
    Icons({
      compiler: 'vue3',
      autoInstall: true,
      customCollections: {
        // a helper to load icons from the file system
        // files under `./assets/icons` with `.svg` extension will be loaded as it's file name
        // you can also provide a transform callback to change each icon (optional)
        'my-icons': FileSystemIconLoader(
          './assets/svg',
          svg => svg.replace(/^<svg /, '<svg fill="currentColor" '),
        ),
      }
    }),
    ViteFonts({
      google: {
        families: ['Open Sans', 'Montserrat', 'Fira Sans'],
      },
    }),
    VueI18n({
      include: [resolve(__dirname, '../locales/**')],
    }),

    Unocss(),
    Markdown({
      wrapperClasses: defaultClasses,
      headEnabled: false,
      markdownItSetup(md) {
        // https://prismjs.com/
        md.use(Prism);
        // 为 md 中的所有链接设置为 新页面跳转
        md.use(LinkAttributes, {
          matcher: (link: string) => /^https?:\/\//.test(link),
          attrs: {
            target: '_blank',
            rel: 'noopener',
          },
        });
      },
    }),
    // mkcert(),
    ConditionalCompile({
      // 'src/**'
      // include:[resolve(__dirname, '../src/**')],
      // exclude:[resolve(__dirname, '../src/assets/**'),resolve(__dirname, '../locales/**'),resolve(__dirname, '../node_modules/**')]
    }),

  ];
};

**Comment by a982246809** [comment]
插件用的最新版 , vite也是最新版

**Comment by a982246809** [comment]
```
/// <reference types="vitest" />
import { defineConfig, loadEnv } from 'vite';
import { resolve } from 'path';
import presets from './presets/presets';

// https://vitejs.dev/config/
export default defineConfig((env) => {
  // env 环境变量
  const viteEnv = loadEnv(env.mode, process.cwd());

  // console.log("🚀  resolve(__dirname, './src'):", resolve(__dirname, './src'));
  // console.log("🚀 resolve(__dirname, 'src/assets/img'):", resolve(__dirname, 'src/assets/img'));

  return {
    base: viteEnv.VITE_BASE,
    // 插件
    plugins: [presets(env, viteEnv)],
    test: {
      deps: {
        interopDefault: true,
        // inline: true,
      },
      // open: true,
      browser: {
        enabled: true,
      },
    },
    // 别名设置
    resolve: {
      alias: {
        // '!': (res) => {
        //   console.log('🚀  res:', res);
        // },
        '@': resolve(__dirname, './src'), // 把 @ 指向到 src 目录去

        '!': resolve(__dirname, 'src/assets/img'), //! 还不可使用
      },
    },
    // 服务设置
    server: {
      // https: true,
      host: true, // host设置为true才可以使用network的形式，以ip访问项目
      port: 8080, // 端口号
      // open: true, // 自动打开浏览器
      cors: true, // 跨域设置允许
      strictPort: true, // 如果端口已占用直接退出
      // 接口代理
      //! 没起作用
      proxy: {
        '/api': {
          // 本地 8000 前端代码的接口 代理到 8888 的服务端口
          target: 'http://localhost:8888/',
          changeOrigin: true, // 允许跨域
          rewrite: (path) => path.replace('/api/', '/'),
        },
        // 走本地接口
        // [process.env.VUE_APP_BASE_API]: {
        //   target: process.env.VUE_APP_BASE_TARGET,
        //   changeOrigin: true,
        //   pathRewrite: {
        //     ['^' + process.env.VUE_APP_BASE_API]: ''
        //   }
        // }
      },
    },
    build: {
      reportCompressedSize: false,
      // 消除打包大小超过500kb警告
      chunkSizeWarningLimit: 2000,
      minify: 'esbuild',
      assetsDir: 'static/assets',
      // 静态资源打包到dist下的不同目录
      rollupOptions: {
        output: {
          chunkFileNames: 'static/js/[name]-[hash].js',
          entryFileNames: 'static/js/[name]-[hash].js',
          assetFileNames: 'static/[ext]/[name]-[hash].[ext]',
        },
      },
    },
    css: {
      preprocessorOptions: {
        // 全局引入了 scss 的文件
        scss: {
          additionalData: `
          @import "@/assets/styles/variables.scss";
        `,
          javascriptEnabled: true,
        },
      },
    },
    define: {
      __Package_VERSION__: JSON.stringify(process.env.npm_package_version),
    },
  };
});
```

**Comment by a982246809** [comment]
presets\presets.ts
```
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import svgLoader from 'vite-svg-loader';
import AutoImport from 'unplugin-auto-import/vite';
import Components from 'unplugin-vue-components/vite';
import Icons from 'unplugin-icons/vite';
// loader helpers
import { FileSystemIconLoader } from 'unplugin-icons/loaders'
import IconsResolver from 'unplugin-icons/resolver';
import { ElementPlusResolver, VantResolver, VueUseComponentsResolver, HeadlessUiResolver, NaiveUiResolver } from 'unplugin-vue-components/resolvers';

import Markdown from 'vite-plugin-vue-markdown'
import Prism from 'markdown-it-prism';
import ViteFonts from 'vite-plugin-fonts';
// import VueI18n from '@intlify/vite-plugin-vue-i18n';
import VueI18n from '@intlify/unplugin-vue-i18n/vite'
import LinkAttributes from 'markdown-it-link-attributes';
import Unocss from 'unocss/vite'
import { ConfigEnv } from 'vite';
import { resolve } from 'path';
import mkcert from 'vite-plugin-mkcert'
import { VitePWA } from 'vite-plugin-pwa'
import ConditionalCompile from "vite-plugin-conditional-compiler";
const defaultClasses = 'prose prose-sm m-auto text-left';

export default (env: ConfigEnv, viteEnv) => {
  return [

    VitePWA({
      devOptions: {
        // enabled: true
        /* other options */
      },
      registerType: 'autoUpdate',
      manifest: {
        "name": viteEnv.VITE_APP_TITLE,
        "short_name": viteEnv.VITE_APP_TITLE,
        "start_url": ".",
        "display": "standalone",
        "background_color": "#1f1f1f",
        "description": viteEnv.VITE_APP_TITLE,
        "icons": [
          // {
          //   "src": "favicon.png",
          //   "sizes": "144x144",
          //   "type": "image/png"
          // },
          {
            "src": "favicon.png",
            "sizes": "72x72",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "96x96",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "144x144",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "168x168",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "192x192",
            "type": "image/png"
          },
          {
            "src": "favicon.png",
            "sizes": "256x256",
            "type": "image/png"
          }
        ]
      }
    }),
    vue({
      include: [/\.vue$/, /\.md$/],
      template: {
        // 解决警告
        // Failed to resolve component: swiper-container
        // If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
        compilerOptions: {
          isCustomElement: (tag) => ['swiper-container', 'swiper-slide'].includes(tag),
        },
      }

    }),
    vueJsx(),
    svgLoader(),
    AutoImport({
      dts: './src/auto-imports.d.ts',
      imports: ['vue', 'pinia', 'vue-router', 'vue-i18n', , '@vueuse/core', {
        'naive-ui': [
          'useDialog',
          'useMessage',
          'useNotification',
          'useLoadingBar'
        ]
      }],
      // Generate corresponding .eslintrc-auto-import.json file.
      // eslint globals Docs - https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals
      eslintrc: {
        enabled: false, // Default `false`
        filepath: './.eslintrc-auto-import.json', // Default `./.eslintrc-auto-import.json`
        globalsPropValue: true, // Default `true`, (true | false | 'readonly' | 'readable' | 'writable' | 'writeable')
      },
      resolvers: [ElementPlusResolver()],
    }),
    Components({
      dts: './src/components.d.ts',
      extensions: ['vue', 'md', 'svg'],
      include: [/\.vue$/, /\.vue\?vue/, /\.md$/,],
      // imports 指定组件所在位置，默认为 src/components; 有需要也可以加上 view 目录
      // dirs: ['src/components/'],
      dirs: ['src'],
      resolvers: [ElementPlusResolver(), IconsResolver({
        customCollections: [
          'my-icons',
        ],
      }), VueUseComponentsResolver(), HeadlessUiResolver(), NaiveUiResolver(), VantResolver()],
    }),
    Icons({
      compiler: 'vue3',
      autoInstall: true,
      customCollections: {
        // a helper to load icons from the file system
        // files under `./assets/icons` with `.svg` extension will be loaded as it's file name
        // you can also provide a transform callback to change each icon (optional)
        'my-icons': FileSystemIconLoader(
          './assets/svg',
          svg => svg.replace(/^<svg /, '<svg fill="currentColor" '),
        ),
      }
    }),
    ViteFonts({
      google: {
        families: ['Open Sans', 'Montserrat', 'Fira Sans'],
      },
    }),
    VueI18n({
      include: [resolve(__dirname, '../locales/**')],
    }),

    Unocss(),
    Markdown({
      wrapperClasses: defaultClasses,
      headEnabled: false,
      markdownItSetup(md) {
        // https://prismjs.com/
        md.use(Prism);
        // 为 md 中的所有链接设置为 新页面跳转
        md.use(LinkAttributes, {
          matcher: (link: string) => /^https?:\/\//.test(link),
          attrs: {
            target: '_blank',
            rel: 'noopener',
          },
        });
      },
    }),
    // mkcert(),
    ConditionalCompile({
      // 'src/**'
      // include:[resolve(__dirname, '../src/**')],
      // exclude:[resolve(__dirname, '../src/assets/**'),resolve(__dirname, '../locales/**'),resolve(__dirname, '../node_modules/**')]
    }),

  ];
};

```

**Comment by KeJunMao** [comment]
换成这个版本试试 [v0.1.1](https://github.com/KeJunMao/vite-plugin-conditional-compile/releases/tag/v0.1.1)

这个版本纯正则实现，缺点就是不支持嵌套

**Comment by a982246809** [comment]
换0.1.1的版本 , 就可以了 , 但没设置环境变量的时候老报警告
vite-plugin-conditional-compile] No 'VITE_ID' propertie in Vite environment variables (x10)

**Comment by a982246809** [comment]
> 换0.1.1的版本 , 就可以了 , 但没设置环境变量的时候老报警告 vite-plugin-conditional-compile] No 'VITE_ID' propertie in Vite environment variables (x10)

设置`VITE_ID=false` , 会编译成字符串'false' , 结果判断为还是true了

**Comment by KeJunMao** [comment]
我抽空看看0.2.0的性能问题

**Comment by KeJunMao** [comment]
共 99567 个文件，开始测试: 

stdout | test/directives/pref.test.ts > perf > if
平均每个文件 1.752228449184971 ms， 总耗时 174.46 s

哥，你项目有9w+个文件吗

**Comment by a982246809** [comment]
主要我第一次启动是正常 , 第二次关掉再启动vite才会卡 .
而且我试过只包含src文件夹 也一样卡

**Comment by KeJunMao** [comment]
@a982246809 你好，请问您可以更新到最新版本吗，性能有了巨大提升（174s -> 20s）

**Comment by a982246809** [comment]
我试试

**Comment by a982246809** [comment]
奇怪 , 我明明是这样设的版本^0.1.1 , 它没跟我自动更新次级版本

**Comment by KeJunMao** [comment]
我一般使用下面的命令更新依赖~
```bash
pnpx taze -I -r
```

**Comment by yaoyuan00** [comment]
> 奇怪 , 我明明是这样设的版本^0.1.1 , 它没跟我自动更新次级版本

根据semver, 在0.x.y中, 认为是还是不稳定版本, 所以x变化, 即意味着有breaking change. 所以没自动更新是正确的.

1.0.0这种x.y.z以后, 则认为是对外发布的稳定版
